export const CORE_KEYWORDS = {
  date: {
    exact: [
      "data",
      "date",
      "dato",
      "data operazione",
      "data contabile",
      "data movimento",
      "data registrazione",
      "booking date",
      "transaction date",
      "posting date",
      "bokforingsdato",
      "transaksjonsdato",
      "buchungsdatum",
      "fecha",
    ],
    words: ["data", "date", "dato", "datum", "fecha"],
  },
  description: {
    exact: [
      "descrizione",
      "description",
      "causale",
      "dettagli",
      "dettaglio",
      "movimento",
      "operazione",
      "memo",
      "details",
      "narrative",
      "payee",
      "merchant",
      "forklaring",
      "tekst",
      "beskrivelse",
      "mottaker",
      "transaksjon",
      "note",
      "notes",
      "reference",
      "riferimento",
    ],
    words: [
      "descrizione",
      "description",
      "causale",
      "dettagli",
      "movimento",
      "narrative",
      "payee",
      "merchant",
      "forklaring",
      "beskrivelse",
      "tekst",
      "mottaker",
      "details",
      "memo",
    ],
  },
  amount: {
    exact: [
      "importo",
      "amount",
      "belop",
      "ammontare",
      "valore",
      "value",
      "betrag",
    ],
    words: ["importo", "amount", "belop", "ammontare", "betrag"],
  },
};
