export const FLOW_KEYWORDS = {
  debit: {
    exact: [
      "dare",
      "uscite",
      "uscita",
      "addebito",
      "addebiti",
      "debit",
      "withdrawal",
      "withdrawals",
      "paid out",
      "money out",
      "ut",
      "ut fra konto",
      "uttak",
      "belast",
    ],
    words: [
      "dare",
      "uscite",
      "addebiti",
      "addebito",
      "debit",
      "withdrawal",
      "uttak",
    ],
  },
  credit: {
    exact: [
      "avere",
      "entrate",
      "entrata",
      "accredito",
      "accrediti",
      "credit",
      "deposit",
      "deposits",
      "paid in",
      "money in",
      "inn",
      "inn pa konto",
      "innskudd",
    ],
    words: [
      "avere",
      "entrate",
      "accrediti",
      "accredito",
      "credit",
      "deposit",
      "innskudd",
    ],
  },
  sign: {
    exact: [
      "segno",
      "d a",
      "dare avere",
      "tipo",
      "tipo movimento",
      "tipo operazione",
      "tipologia",
      "verso",
      "debit credit",
      "credit debit",
      "db cr",
      "cr db",
      "dc",
      "type",
      "transaction type",
      "indicator",
    ],
    words: ["segno", "tipo", "tipologia", "verso", "indicator"],
  },
  currency: {
    exact: [
      "valuta",
      "divisa",
      "currency",
      "cur",
      "ccy",
      "moneta",
      "valutakode",
    ],
    words: ["currency", "divisa", "valutakode"],
  },
  balance: {
    exact: [
      "saldo",
      "balance",
      "saldo contabile",
      "saldo disponibile",
      "running balance",
    ],
    words: ["saldo", "balance"],
  },
};
