export const TX_CURRENCIES = [
  { code: "EUR", name: "Euro" },
  { code: "NOK", name: "Corona norvegese" },
  { code: "USD", name: "Dollaro USA" },
  { code: "GBP", name: "Sterlina" },
  { code: "SEK", name: "Corona svedese" },
  { code: "DKK", name: "Corona danese" },
  { code: "CHF", name: "Franco svizzero" },
  { code: "CAD", name: "Dollaro canadese" },
  { code: "AUD", name: "Dollaro australiano" },
  { code: "JPY", name: "Yen" },
  { code: "CNY", name: "Yuan" },
  { code: "INR", name: "Rupia indiana" },
  { code: "BRL", name: "Real" },
  { code: "MXN", name: "Peso messicano" },
  { code: "SGD", name: "Dollaro di Singapore" },
  { code: "HKD", name: "Dollaro di Hong Kong" },
  { code: "KRW", name: "Won" },
  { code: "PLN", name: "Zloty" },
  { code: "CZK", name: "Corona ceca" },
  { code: "HUF", name: "Fiorino" },
  { code: "RON", name: "Leu" },
  { code: "TRY", name: "Lira turca" },
  { code: "ZAR", name: "Rand" },
  { code: "RUB", name: "Rublo" },
  { code: "SAR", name: "Riyal" },
  { code: "AED", name: "Dirham" },
  { code: "NZD", name: "Dollaro neozelandese" },
  { code: "THB", name: "Baht" },
  { code: "MYR", name: "Ringgit" },
  { code: "IDR", name: "Rupia indonesiana" },
];
